### ISSUE TITLE
[icub] left arm skin not working

### ISSUE THREAD

**Issue by serena-ivaldi** [inria-larsen/robots-status#1]
Found launching skinManager, it shows that the left arm skin is not working (0 taxels).
Could be a problem of a disconnected cable?

**Comment by dogoepp** [comment]
How can I help to answer this question ?

**Comment by jbmouret** [comment]
We should probably open the arm again and have a look...

-- JBM

**Comment by dogoepp** [comment]
Sure, unmounting is a thing to do. It's also more useful if we narrowed 
as much as possible the cause of the problem beforehand.

Hence, are there some errors or messages that could guide us to a more 
precise diagnosis ? For instance, does robotInterface tell that one card 
is not responding ?

**Comment by dogoepp** [comment]
Maybe we can have a look together today, Serena ? You know better the messages and software of iCub and could spot something that I don't see.

**Comment by serena-ivaldi** [comment]
The robotinterface says ok, the error we found yesterday is about the left_arm skin that is not responding. the error can be found on the skinManager, that connecting to the skin sees 0 taxels and says "not working". Indeed there is no contact detected on the skin of the left arm. Our suspicion is that there is a loose cable somewhere connecting the skin (hardware) to its board. Anthony said that could be something misplaced when mounting/unmounting

**Comment by serena-ivaldi** [comment]
We fixed this yesterday with @dogoepp and Alex. There was a problem in the wiring when we put back the cover. There was one loose connector. It is fixed now. We tested the skin and it's ok.
